//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface AccountModel {
    Id: string;
    UserName: string;
    Location: LocationModel;
}

export interface LocationModel {
    City: string;
    Postcode: string;
    Street: string;
    Number: string;
    Longitude: number;
    Latitude: number;
}

export interface ItemRequest {
    Barcode: string;
    Name: string;
    Details: string;
    Quantity: number;
    Unit: string;
    Creator: Account;
}

export interface IdentityUserOfString {
    Id?: string | undefined;
    UserName?: string | undefined;
    NormalizedUserName?: string | undefined;
    Email?: string | undefined;
    NormalizedEmail?: string | undefined;
    EmailConfirmed: boolean;
    PasswordHash?: string | undefined;
    SecurityStamp?: string | undefined;
    ConcurrencyStamp?: string | undefined;
    PhoneNumber?: string | undefined;
    PhoneNumberConfirmed: boolean;
    TwoFactorEnabled: boolean;
    LockoutEnd?: Date | undefined;
    LockoutEnabled: boolean;
    AccessFailedCount: number;
}

export interface IdentityUser extends IdentityUserOfString {
}

export interface Account extends IdentityUser {
    Id: string;
    Location?: Location | undefined;
}

export interface Location {
    Id: number;
    City: string;
    Postcode: string;
    Street: string;
    Number: string;
    Longitude: number;
    Latitude: number;
}

export interface LoginRequest {
    Email: string;
    Password: string;
}

export interface RefreshTokenRequest {
    RefreshToken: string;
}

export interface RegisterRequest {
    UserName: string;
    Password: string;
    Email: string;
}

export interface RegisterShopRequest {
    Company: string;
    Password: string;
    Email: string;
    Location: LocationModel;
}

export interface ShopRequest {
    Name: string;
    Details: string;
    CompanyName: string;
    Location: LocationModel;
    OpeningHours?: OpeningHoursModel[] | undefined;
}

export interface OpeningHoursModel {
    DayOfWeek: DayOfWeek;
    StartTime: string;
    EndTime: string;
}

export enum DayOfWeek {
    Sunday = 0,
    Monday = 1,
    Tuesday = 2,
    Wednesday = 3,
    Thursday = 4,
    Friday = 5,
    Saturday = 6,
}

export interface ItemResponse {
    Barcode: string;
    Name: string;
    Details: string;
    Quantity: number;
    Unit: string;
    Creator: Account;
}

export interface JwtAuthResult {
    AccessToken: string;
    RefreshToken: RefreshToken;
    Roles: string[];
}

export interface JwtAuthResponse extends JwtAuthResult {
}

export interface RefreshToken {
    UserName: string;
    TokenString: string;
    ExpireAt: Date;
}

export interface LoginResponse {
    UserName: string;
    Role: string;
    OriginalUserName: string;
    AccessToken: string;
    RefreshToken: string;
    Email: string;
}

export interface RegisterResponse {
    Message: string;
}

export interface ShopResponse {
    Id: number;
    Name: string;
    Details: string;
    Location: LocationModel;
    Creator: AccountModel;
    Company: AccountModel;
    OpeningHours?: OpeningHoursModel[] | undefined;
}