//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.20.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface LoginRequest {
    UserName: string;
    Password: string;
}

export interface RefreshTokenRequest {
    RefreshToken: string;
}

export interface RegisterRequest {
    UserName: string;
    Password: string;
    Email: string;
}

export interface LoginResponse {
    UserName: string;
    Role: string;
    OriginalUserName: string;
    AccessToken: string;
    RefreshToken: string;
    Email: string;
}

export interface JwtAuthResult {
    AccessToken: string;
    RefreshToken: RefreshToken;
}

export interface JwtAuthResponse extends JwtAuthResult {
}

export interface RefreshToken {
    UserName: string;
    TokenString: string;
    ExpireAt: Date;
}

export interface RegisterResponse {
    Message: string;
}